### ISSUE TITLE
Officially maintained fork supports rails4

### ISSUE THREAD

**Issue by bigtunacan** [peterwillcn/rails4-autocomplete#28]
@peterwillcn It looks like you forked this from https://github.com/crowdint/rails3-jquery-autocomplete back when it wasn't yet supporting Rails 4 and the project had gone pretty inactive.

David handed the project off to me as the primary maintainer some time ago and we do have support for Rails 4 these days.  The official repo location is at https://github.com/bigtunacan/rails-jquery-autocomplete.

Since you are no longer maintaining this fork, if you want to redirect there from the README that would be good.  If you give me permissions on this repo to maintain I can close out issues and pull requests here as I move them over to the other fork & groom the backlog.

**Comment by jfouse** [comment]
Bump.  Was just looking through these two repos myself trying to figure out the difference, and then realized they shared ancestry.  Thanks for clarifying @bigtunacan.  Would definitely be good to get the discrepancy cleaned up for the community's sake.

**Comment by bigtunacan** [comment]
@jfouse Closing as @peterwillcn has since updated the main page here to point over to the other repo.
