### ISSUE TITLE
User authentication issue

### ISSUE THREAD

**Issue by Rubioli** [peterwillcn/rails4-autocomplete#40]
I am using rails4-autocomplete for **users controller & model** for finding **city id**. Everything works fine until if I want user to search for city_name/city_id in **registration process** (Im using devise).

When I am not logged in and try to go to **http://localhost:3000/users/autocomplete_city_name**, I am being redirected to login page since I am not logged in and when I am logged in, it works fine.

How can make the route so it doesn't need any authentication for autocomplete.

This is my route:
```
devise_for :users
resources :users do
    get :autocomplete_city_name, :on => :collection
  end
```

My current controller:
```
class UsersController < ApplicationController
  autocomplete :city, :name, :full => false, :display_value => :state_country_name, :extra_data => [:state_id]
end
```

Thanks in advanced!

**Comment by ohadco** [comment]
class UsersController < ApplicationController
skip_before_filter :authenticate_user!, :only => [ :index ]
  autocomplete :city, :name, :full => false, :display_value => :state_country_name, :extra_data => [:state_id]
end

**Comment by ohadco** [comment]
Just add this to your UsersController:

`skip_before_filter :authenticate_user!, :only => [:autocomplete_city_name]`

Might be a bit different action name..

**Comment by Rubioli** [comment]
Thanks for all answers.

What worked was:
`before_action :authenticate_user!, :except => [:autocomplete_city_name]`
