### ISSUE TITLE
How to limit the number of returned results to a specified maximum number of matches

### ISSUE THREAD

**Issue by acrolink** [peterwillcn/rails4-autocomplete#47]
I am using this gem on a table with over 1000 records. Many of rows share string parts on the lookup column. When I start typing it returns a list of many results, something that causes the browser to hang little bit. It would be nice to limit the returned results (autocomplete results) to say a maximum of 20 results. How to do that? Thank you.

**Comment by aaltheiab2012** [comment]
You should have 'limit' in the query, this should solve the problem

**Comment by acrolink** [comment]
@aaltheiab2012 

Thank you. I have just forgot that I can simply use the Activerecod SQL query interface..
