### ISSUE TITLE
Conflict with active_model_serializer gem

### ISSUE THREAD

**Issue by Rodrigora** [peterwillcn/rails4-autocomplete#9]
After adding the active_model_serializer gem , the autocomplete stopped to work. It happens due to serialzer that adds root key to JSON. 

Has option to remove root key from autocomplete generated action?

```ruby
class CitiesController < ApplicationController
  autocomplete :city, :name, full: true

  #  autocomplete :city, :name, full: true, serializer: nil
end
```

**Comment by lucasbiguet** [comment]
I know this is old, but I've just encountered this bug and fixed it thanks to this SO post: http://stackoverflow.com/questions/15350859/make-root-node-in-active-model-serializer

I added this to ApplicationController (just be aware it will affect ALL your serializers)
def default_serializer_options
  {root: false}
end

This is a workaround though and I think it would be a good idea to add an option on 'autocomplete' as suggested above.

**Comment by Rodrigora** [comment]
Thank you @lucasbiguet.

I don't have this issue anymore.
